tasks:
  - name: run
    command: |
      npm install
      npm run build
      python3 -m venv venv
      source venv/bin/activate
      pip install -r requirements.txt
      deactivate
      yarn start
    env:
      FLASK_RUN_PORT: 5000
