tasks:
  - name: run
    command: |
      python3 -m venv venv
      source venv/bin/activate
      pip install -r requirements.txt
      deactivate
      yarn start-api
    env:
      FLASK_RUN_PORT: 5000
  - name: frontend
    command: |
      npm install
      yarn start
    env:
      REACT_APP_HOST: http://localhost:5000
      PORT: 5030